spring:
  profiles:
    active: dev
    include: satoken
  application:
    name: admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  config: classpath:logback.xml